version: '3'

services:
  app:
    build: ./app
    restart: always
    ports:
      - 80:80
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
   
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
